export const termAliases: Record<string, string[]> = {
  mask: ['immobilisation', 'immobilization', 'thermoplastic', 'mould', 'mold', 'positioning'],
  planning: ['simulation', 'ct', 'scan', 'contouring', 'qa', 'quality', 'approval'],
  scan: ['ct', 'simulation', 'imaging', 'mri', 'pet'],
  radiation: ['rt', 'ebrt', 'radiotherapy', 'therapy'],
  burning: ['burn', 'manta', 'irritation', 'sore'],
  pain: ['noppi', 'ache', 'discomfort'],
  mouth: ['oral', 'norulo', 'mucositis', 'gargle'],
  swallowing: ['swallow', 'mingadam', 'dysphagia', 'throat', 'gonthu'],
  food: ['tindi', 'diet', 'nutrition', 'meals', 'solids'],
  water: ['neellu', 'fluids', 'liquids', 'hydration'],
  urine: ['urinary', 'bladder', 'urination', 'cystitis'],
  motion: ['bowel', 'stool', 'diarrhea', 'constipation'],
  skin: ['charma', 'reaction', 'soap', 'lotion', 'cream'],
  hair: ['juttu', 'shaving', 'fall'],
  neck: ['head', 'throat', 'gonthu'],
  breast: ['chest', 'axilla'],
  chest: ['thorax', 'lung', 'breast'],
  stomach: ['abdomen', 'nausea', 'vomiting'],
  pelvis: ['pelvic', 'bladder', 'rectal', 'urine'],
  exercise: ['rehabilitation', 'physiotherapy', 'shoulder', 'neck'],
}

export const romanizedTeluguAliases: Record<string, string[]> = {
  enduku: ['why'],
  enti: ['what'],
  eppudu: ['when'],
  ayyaka: ['after'],
  avuthundi: ['happens'],
  chestara: ['call', 'inform', 'notify'],
  vestaru: ['use', 'wear', 'put'],
  noppi: ['pain'],
  manta: ['burning', 'irritation'],
  tindi: ['food', 'diet'],
  neellu: ['water', 'fluids'],
  mingadam: ['swallowing'],
  norulo: ['mouth', 'oral'],
  gonthu: ['throat', 'swallowing'],
  juttu: ['hair'],
  charma: ['skin'],
}

export const teluguScriptAliases: Array<[RegExp, string]> = [
  [/రేడియేషన్/g, ' radiation '],
  [/థెరపీ/g, ' therapy '],
  [/మాస్క్?|ముసుగు/g, ' mask '],
  [/ఎందుకు/g, ' why '],
  [/ఏమి|ఏంటి/g, ' what '],
  [/ఎప్పుడు/g, ' when '],
  [/నొప్పి/g, ' pain '],
  [/మంట/g, ' burning '],
  [/ప్లానింగ్/g, ' planning '],
  [/స్కాన్/g, ' scan '],
  [/నోరు/g, ' mouth '],
  [/గొంతు/g, ' throat '],
  [/చర్మం/g, ' skin '],
  [/దుష్ప్రభావాలు/g, ' side effects '],
]
